Repository Eleks-Internship/clother, pull requests merged in 2021-02, with the labels that each got.

#95 52/save user
  clother-node/package-lock.json
  clother-node/package.json
  clother-node/src/api/v1/user.api.ts
  clother-node/src/api/v1/v1.api.ts
  clother-node/src/database/database_info.ts
  clother-node/src/database/user/user.database.ts
  clother-node/src/interface/object/user.ts
  clother-node/src/services/auth/auth.service.ts
  clother-node/src/services/auth/login.service.ts
  clother-node/src/services/user/password.service.ts
  clother-node/src/services/user/user.service.ts
  clother-node/test/api/user/user.api.test.ts
  clother-node/test/database/user/user.database.test.ts
  clother-node/test/services/auth/auth.service.test.ts
  clother-node/test/services/auth/login.service.test.ts
  clother-node/test/services/user/passwrod.service.test.ts
  clother-node/test/services/user/user.service.test.ts
Labels: back end

#111 Questionnaire of questions for girls and boys
  max.png
  tanya.png
  template.png
Labels: business analytics

#107 Feature/33 create page for login
  clother-angular/src/app/app-routing.module.ts
  clother-angular/src/app/app.module.ts
  clother-angular/src/app/components/login-form/login-form.component.html
  clother-angular/src/app/components/login-form/login-form.component.scss
  clother-angular/src/app/components/login-form/login-form.component.spec.ts
  clother-angular/src/app/components/login-form/login-form.component.ts
  clother-angular/src/app/components/sign-up-form/sign-up-form.component.scss
  clother-angular/src/app/pages/login/login.component.html
  clother-angular/src/app/pages/login/login.component.scss
  clother-angular/src/app/pages/login/login.component.spec.ts
  clother-angular/src/app/pages/login/login.component.ts
  clother-angular/src/app/pages/sign-up/sign-up.component.scss
  clother-angular/src/app/service/http.service.ts
  clother-angular/src/app/service/login.service.spec.ts
  clother-angular/src/app/service/login.service.ts
  clother-angular/src/styles.scss
Labels: front end

#115 #45 Create guard for login user
  clother-angular/package-lock.json
  clother-angular/package.json
  clother-angular/src/app/app-routing.module.ts
  clother-angular/src/app/app.module.ts
  clother-angular/src/app/components/login-by-social-media/login-by-social-media.component.html
  clother-angular/src/app/components/login-by-social-media/login-by-social-media.component.scss
  clother-angular/src/app/components/login-by-social-media/login-by-social-media.component.spec.ts
  clother-angular/src/app/components/login-by-social-media/login-by-social-media.component.ts
  clother-angular/src/app/guards/login.guard.spec.ts
  clother-angular/src/app/guards/login.guard.ts
  clother-angular/src/app/pages/login/login.component.html
  clother-angular/src/app/pages/sign-up/sign-up.component.html
  clother-angular/src/app/service/http.service.ts
  clother-angular/src/app/service/login.service.ts
  clother-angular/src/assets/img/facebook.png
  clother-angular/src/assets/img/google.png
  clother-angular/tsconfig.json
  clother-node/src/api/v1/login.api.ts
  clother-node/src/services/auth/login.service.ts
  clother-node/test/api/login/login.test.ts
  clother-node/test/services/auth/login.service.test.ts
Labels: front end

#74 Project management
  project-management/Communication Management Plan.pdf
  project-management/Penetration testing results.pdf
  project-management/RAID log.pdf
  project-management/Software Requirements Specification (SRS).pdf
  project-management/Stakeholder Register.pdf
  project-management/WBS.pdf
Labels: project management

#121 #105 Add logging for http request
  clother-node/src/services/api.service.ts
Labels: back end

#119 #65 Delete look
  clother-node/src/api/v1/look.api.ts
  clother-node/src/database/look/look.database.ts
  clother-node/src/services/look/look.service.ts
  clother-node/test/api/look/look.api.test.ts
  clother-node/test/database/look/look.database.test.ts
  clother-node/test/services/look/look.service.test.ts
Labels: back end

#120 #57 Get wardrobe
  clother-node/src/api/v1/look.api.ts
  clother-node/src/api/v1/user.api.ts
  clother-node/src/database/clothes/clothes.database.ts
  clother-node/src/database/database_object.ts
  clother-node/src/interface/class/get_list_of_user.ts
  clother-node/src/services/clothes/clothes.service.ts
  clother-node/test/api/user/user.api.test.ts
  clother-node/test/database/clothes/clothes.database.test.ts
  clother-node/test/services/clothes/clothes.service.test.ts
Labels: back end

#133 #130 Connect main server to server of generate looks
  clother-angular/Dockerfile
  clother-angular/package.json
  clother-angular/src/environments/environment.prod.ts
  clother-angular/src/environments/environment.ts
  clother-node/package-lock.json
  clother-node/package.json
  clother-node/src/api/v1/recommendation.api.ts
  clother-node/src/api/v1/v1.api.ts
Labels: back end

#122 #67 Like look
  clother-node/src/api/v1/look.api.ts
  clother-node/src/database/collection/collection.database.ts
  clother-node/src/database/look/like_for_look.database.ts
  clother-node/src/interface/object/like_for_look.ts
  clother-node/src/services/auth/auth.service.ts
  clother-node/src/services/auth/login.service.ts
  clother-node/src/services/look/like_for_look.service.ts
  clother-node/test/api/look/look.api.test.ts
  clother-node/test/database/collection/collection.database.test.ts
  clother-node/test/database/look/like_for_look.database.test.ts
  clother-node/test/services/auth/auth.service.test.ts
  clother-node/test/services/auth/login.service.test.ts
  clother-node/test/services/look/like_for_look.service.test.ts
Labels: back end

#124 #70 Get list of look likes and #69 delete like of look
  clother-node/src/api/v1/like.api.ts
  clother-node/src/api/v1/look.api.ts
  clother-node/src/api/v1/v1.api.ts
  clother-node/src/database/look/like_for_look.database.ts
  clother-node/src/services/look/like_for_look.service.ts
  clother-node/test/api/look/like.api.test.ts
  clother-node/test/database/look/like_for_look.database.test.ts
  clother-node/test/services/look/like_for_look.service.test.ts
Labels: back end

#135 #134 Open access for server with angular
  clother-node/Dockerfile
  clother-node/package-lock.json
  clother-node/package.json
  clother-node/src/index.ts
Labels: back end, devops

#137 #129 Save photo to database
  clother-node/.gitignore
  clother-node/package-lock.json
  clother-node/package.json
  clother-node/src/api/v1/clothes.api.ts
  clother-node/src/api/v1/recommendation.api.ts
  clother-node/src/database/clothes/clothes.database.ts
  clother-node/src/database/file/photo_of_clothes.database.ts
  clother-node/src/database/mongodb_url.txt
  clother-node/src/index.ts
  clother-node/src/interface/object/clothes.ts
  clother-node/src/services/clothes/clothes.service.ts
  clother-node/test/api/clothes/clothes.api.test.ts
  clother-node/test/database/clothes/clothes.database.test.ts
  clother-node/test/services/clothes/clothes.service.test.ts
Labels: back end

#142 #141 Get photo from database
  clother-node/src/api/v1/clothes.api.ts
  clother-node/src/index.ts
Labels: back end

#143 #140 Delete photo from database
  clother-node/src/api/v1/clothes.api.ts
  clother-node/src/database/file/photo_of_clothes.database.ts
  clother-node/src/interface/object/chunks.ts
  clother-node/src/interface/object/file.ts
  clother-node/src/services/clothes/clothes.service.ts
  clother-node/src/services/file/photo_of_clothes.service.ts
  clother-node/test/api/clothes/clothes.api.test.ts
  clother-node/test/api/login/login.test.ts
  clother-node/test/api/look/like.api.test.ts
  clother-node/test/api/look/look.api.test.ts
  clother-node/test/api/user/user.api.test.ts
Labels: back end

#144 #139 Updated image and info about new photo
  clother-node/src/api/v1/clothes.api.ts
  clother-node/src/services/clothes/clothes.service.ts
Labels: back end
